---
:logging_enabled: false
:current_health: 100
:base_health: 100
:speed: 3.0
:gravity: 0.6
:max_run_speed: 10.0
:blink_recharge_rate: 0.1
:blink_distance: 200
:jumpheight: 15
:noclip: false
:noclip_speed: 10
