---
:logging_enabled: true
:current_health: 100
:base_health: 100
:speed: 3.0
:gravity: 0.6
:blink_recharge_rate: 10
:blink_distance: 100
:jumpheight: 15
:noclip: false
:noclip_speed: 10
:max_run_speed: 10.0
